name = "ShellCheck4"
version = "0.1.0"
defaultTargets = ["shellcheck4"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

# TODO: Add lean-regex when compatible with Lean 4.26+
# [[require]]
# name = "Regex"
# git = "https://github.com/bergmannjg/regex"
# rev = "main"

[[lean_lib]]
name = "ShellCheck"
srcDir = "."

[[lean_exe]]
name = "shellcheck4"
root = "Main"

[[lean_exe]]
name = "shellcheck4_tests"
root = "ShellCheck.Tests.Main"
